apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  labels:
    app.kubernetes.io/created-by: srgfrancisco
    app.kubernetes.io/type: app
spec:
  replicas: 
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ping-pong
      app.kubernetes.io/name: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
        app.kubernetes.io/name: ping-pong
    spec:
      containers:
      - image: sergiofsfilho/ping-pong:latest
        name: ping-pong
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 128m
            memory: 128Mi
